// src/components/UserInfo/UserInfo.jsx
import { Container, ListGroup } from "react-bootstrap";
import Web3 from "web3";
import { ROLES_NAME } from "../../consts";

export const UserInfo = ({
	login,
	address,
	name,
	role,
	shopAddress,
	children,
}) => {
	return (
		<Container>
			<ListGroup as="dl">
				<ListGroup.Item as="dt">Логин</ListGroup.Item>
				<ListGroup.Item as="dd">{login}</ListGroup.Item>
				<ListGroup.Item as="dt">Адрес кошелька</ListGroup.Item>
				<ListGroup.Item as="dd">{address}</ListGroup.Item>
				<ListGroup.Item as="dt">Имя</ListGroup.Item>
				<ListGroup.Item as="dd">{name}</ListGroup.Item>
				<ListGroup.Item as="dt">Роль</ListGroup.Item>
				<ListGroup.Item as="dd">{ROLES_NAME[role]}</ListGroup.Item>
				{Web3.utils.hexToNumberString(shopAddress) != "0" && (
					<>
						<ListGroup.Item as="dt">Магазин:</ListGroup.Item>
						<ListGroup.Item as="dd">{shopAddress}</ListGroup.Item>
					</>
				)}
				{children}
			</ListGroup>
		</Container>
	);
};

// src/entities/users/ui/user-info.vue
<script setup lang="ts">
import { BListGroup, BListGroupItem } from 'bootstrap-vue';
import { computed } from 'vue';
import { hexToNumberString } from 'web3-utils';
import type { User } from '@/entities/users';
import { ROLES_NAME } from '@/shared/config';

export interface UserInfoProps extends User {}

const props = defineProps<UserInfoProps>();

const showShop = computed(() => {
	return !!props.shopAddress && hexToNumberString(props.shopAddress) !== '0';
});
</script>
<template>
	<b-list-group is="dl">
		<b-list-group-item is="dt">Логин</b-list-group-item>
		<b-list-group-item is="dd">{{ login }}</b-list-group-item>
		<b-list-group-item is="dt">Адрес кошелька</b-list-group-item>
		<b-list-group-item is="dd">{{ address }}</b-list-group-item>
		<b-list-group-item is="dt">Имя</b-list-group-item>
		<b-list-group-item is="dd">{{ name }}</b-list-group-item>
		<b-list-group-item is="dt">Роль</b-list-group-item>
		<b-list-group-item is="dd">{{ ROLES_NAME[role] }}</b-list-group-item>
		<template v-if="showShop">
			<b-list-group-item is="dt">Магазин</b-list-group-item>
			<b-list-group-item is="dd">{{ shopAddress }}</b-list-group-item>
		</template>
		<slot></slot>
	</b-list-group>
</template>
