// src/widgets/users/ui/profile-info.vue
<script setup lang="ts">
import { BListGroupItem } from 'bootstrap-vue';
import { toRef } from 'vue';
import { fromWei } from 'web3-utils';
import { UserInfo, authUserModel } from '@/entities/users';
import { useBalance } from '@/entities/web3';

const profileStore = authUserModel.useAuthUserStore();
const address = toRef(profileStore.user, 'address');
const balance = useBalance(address);
</script>
<template>
	<user-info v-bind="profileStore.user">
		<b-list-group-item is="dt">Баланс</b-list-group-item>
		<b-list-group-item is="dd">{{ fromWei(balance, 'ether') }} ETH</b-list-group-item>
	</user-info>
</template>

// src.old/components/ProfileInfo/ProfileInfo.tsx
import * as React from 'react';
import { ListGroup, Spinner } from 'react-bootstrap';
import { ProfileButtons } from '../ProfileButtons';
import { UserInfo } from '../UserInfo';
import { convert } from '@/utils/converts';
import { useGetBalanceQuery } from '@/models/users';
import { useUser } from '@/hooks/useUser';

export const ProfileInfo: React.FC = () => {
	const { info, isLoading, } = useUser();
	const { data: balance = '0', } = useGetBalanceQuery(info?.address || '', {
		pollingInterval: 100,
	});

	return isLoading ? (
		<Spinner animation='border' />
	) : (
		<UserInfo {...info!}>
			<ListGroup.Item as='dt'>Баланс</ListGroup.Item>
			<ListGroup.Item as='dd'>{convert(balance, 'ether')} ETH</ListGroup.Item>
			{!info!.onRequest && <ProfileButtons role={info!.role} />}
		</UserInfo>
	);
};
